rule bwa_map:
	input:
		"data/genome.fa"
		"data/samples/A.fastq"
	output:
		"mapped_reads/A.bam"
	shell:
		"bwa mem {input} | samtools view -Sb - > {output}"

#Since the rule has multiple input files, Snakemake will concatenate them separated by a whitespace