### Step 1: Mapping specifying the number of threads & input function

configfile: "config.yaml"

rule bwa_map: 
	input:
		"data/genome.fa",
		lambda wildcards: config["samples"][wildcards.sample] 
	output:
		"mapped_reads/{sample}.bam"
	threads: 8
	shell:
		"bwa mem -t {threads} {input} | samtools view -Sb - > {output}"






