### Step 1: Mapping specifying the number of threads 

rule bwa_map: 
	input:
		"data/genome.fa",
		"data/samples/{sample}.fastq"
	output:
		"mapped_reads/{sample}.bam"
	threads: 8
	shell:
		"bwa mem -t {threads} {input} | samtools view -Sb - > {output}"






